=== ayushAcharya96/vehicle-xml/catalog_studentID.xsd
<?xml version="1.0"?>
<!-- <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"> -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="https://www.w3schools.com"
xmlns="https://www.w3schools.com"
elementFormDefault="qualified">

    <xs:element name="vehicle_shop">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" type="xs:string" />
                <xs:element name="address" type="xs:string" />
                <xs:element name="telephone_number" type="xs:string" />
                <xs:element name="web_address" type="xs:anyURI" />
                <xs:element name="logo">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="img">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute type="xs:string" name="src"/>
                                            <xs:attribute type="xs:string" name="alt"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="vehicle" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="brand_name" type="xs:string" />
                            <xs:element name="description" type="xs:string" />
                            <xs:element name="quantity" type="xs:string" />
                            <xs:element name="car">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="color" type="xs:string" />
                                        <xs:element name="price" type="xs:string" />
                                        <xs:element name="number_of_doors" type="xs:string" />
                                        <xs:element name="engine">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="xs:string">
                                                        <xs:attribute name="number_of_cylinder" type="xs:string" use="optional" />
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="year" type="xs:integer" use="optional" />
                                    <xs:attribute name="model" type="xs:string" use="optional" />
                                    <xs:attribute name="carType" type="xs:string" use="optional" />
                                    <xs:attribute name="manufacturer" type="xs:string" use="optional" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="category" type="xs:string" use="optional" />
                        <xs:attribute name="item_number" type="xs:string" use="optional" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== ayushAcharya96/vehicle-xml/catalog_studentID.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="catalog_studentID.css"?> 
<vehicle_shop xmlns="http://www.w3.org/1999/xhtml" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://www.w3.org catalog_studentID.xsd">
    <logo>
        <img src="index.png" /> 
    </logo>
    <name>ABC Company</name>
    <address>Kathmandu, Nepal</address>
    <telephone_number>(+977) 9867676767</telephone_number>
    <web_address>www.sales.abc.com</web_address>
    <vehicle category="sedan" item_number="1">
        <brand_name>Hyundai</brand_name>
        <description>In great condition.</description>
        <quantity>3 cars available</quantity>
        <car year="2012" model="Impala" carType="fuel" manufacturer="Hynudai">
            <color>Red Color</color>
            <price>$8000</price>
            <number_of_doors>4 doors</number_of_doors>
            <engine number_of_cylinder="8 cylinders"></engine>
        </car>
    </vehicle>
    <vehicle category="hatchback" item_number="2">
        <brand_name>Ford</brand_name>
        <description>In great condition.</description>
        <quantity>3 available</quantity>
        <car year="2012" model="Impala" carType="fuel" manufacturer="Ford">
            <color>Blue in color</color>
            <price>$10000</price>
            <number_of_doors>4 doors</number_of_doors>
            <engine number_of_cylinder="8 cylinders"></engine>
        </car>
    </vehicle>
    <vehicle category="sedan" item_number="3">
        <brand_name>Toyoto</brand_name>
        <description>In great condition.</description>
        <quantity>3 available</quantity>
        <car year="2016" model="Impala" carType="fuel" manufacturer="Toyota">
            <color>Silver color</color>
            <price>$15000</price>
            <number_of_doors>4 doors</number_of_doors>
            <engine number_of_cylinder="8 cylinders"></engine>
        </car>
    </vehicle>
    <vehicle category="suv" item_number="4">
        <brand_name>Toyota</brand_name>
        <description>Bought last year. Is still in great condition.</description>
        <quantity>2 available</quantity>
        <car year="2016" model="Fortuner" carType="fuel" manufacturer="Toyota">
            <color>Black color</color>
            <price>$10000</price>
            <number_of_doors>4 doors</number_of_doors>
            <engine number_of_cylinder="8 cylinders"></engine>
        </car>
    </vehicle>
    <vehicle category="sedan" item_number="5">
        <brand_name>Toyoto</brand_name>
        <description>In great condition.</description>
        <quantity>3 available</quantity>
        <car year="2018" model="Yaris" carType="fuel" manufacturer="Toyota">
            <color>Silver color</color>
            <price>$12000</price>
            <number_of_doors>4 doors</number_of_doors>
            <engine number_of_cylinder="8 cylinders"></engine>
        </car>
    </vehicle>
    <vehicle category="suv" item_number="6">
        <brand_name>Ford</brand_name>
        <description>In great condition.</description>
        <quantity>3 available</quantity>
        <car year="2015" model="Eco Sport" carType="fuel" manufacturer="Ford">
            <color>Red color</color>
            <price>$15000</price>
            <number_of_doors>4 doors</number_of_doors>
            <engine number_of_cylinder="8 cylinders"></engine>
        </car>
    </vehicle>
    <vehicle category="sedan" item_number="7">
        <brand_name>Toyoto</brand_name>
        <description>In great condition.</description>
        <quantity>3 available</quantity>
        <car year="2019" model="Corolla" carType="fuel" manufacturer="Toyota">
            <color>Silver color</color>
            <price>$20000</price>
            <number_of_doors>4 doors</number_of_doors>
            <engine number_of_cylinder="8 cylinders"></engine>
        </car>
    </vehicle>
    <vehicle category="suv" item_number="8">
        <brand_name>Toyoto</brand_name>
        <description>In great condition.</description>
        <quantity>3 available</quantity>
        <car year="2019" model="Impala" carType="fuel" manufacturer="Toyota">
            <color>Silver color</color>
            <price>$18000</price>
            <number_of_doors>4 doors</number_of_doors>
            <engine number_of_cylinder="8 cylinders"></engine>
        </car>
    </vehicle>
    <vehicle category="suv" item_number="9">
        <brand_name>Toyoto</brand_name>
        <description>In great condition.</description>
        <quantity>3 available</quantity>
        <car year="2016" model="Impala" carType="fuel" manufacturer="Toyota">
            <color>Black color</color>
            <price>$15000</price>
            <number_of_doors>4 doors</number_of_doors>
            <engine number_of_cylinder="8 cylinders"></engine>
        </car>
    </vehicle>
    <vehicle category="suv" item_number="10">
        <brand_name>Toyoto</brand_name>
        <description>In great condition.</description>
        <quantity>3 available</quantity>
        <car year="2016" model="Impala" carType="fuel" manufacturer="Toyota">
            <color>Red color</color>
            <price>$14000</price>
            <number_of_doors>4 doors</number_of_doors>
            <engine number_of_cylinder="8 cylinders"></engine>
        </car>
    </vehicle>
    <vehicle category="suv" item_number="11">
        <brand_name>Toyoto</brand_name>
        <description>In great condition.</description>
        <quantity>3 available</quantity>
        <car year="2016" model="Impala" carType="fuel" manufacturer="Toyota">
            <color>Gray color</color>
            <price>$15000</price>
            <number_of_doors>4</number_of_doors>
            <engine number_of_cylinder="8 cylinders"></engine>
        </car>
    </vehicle>
    <vehicle category="sedan" item_number="12">
        <brand_name>Toyoto</brand_name>
        <description>In great condition.</description>
        <quantity>3 available</quantity>
        <car year="2016" model="Corolla" carType="fuel" manufacturer="Toyota">
            <color>Silver color</color>
            <price>$15000</price>
            <number_of_doors>4 doors</number_of_doors>
            <engine number_of_cylinder="8 cylinders"></engine>
        </car>
    </vehicle>
    <vehicle category="sedan" item_number="13">
        <brand_name>Toyoto</brand_name>
        <description>In great condition.</description>
        <quantity>3 available</quantity>
        <car year="2019" model="corolla" carType="fuel" manufacturer="Toyota">
            <color>Black color</color>
            <price>$18000</price>
            <number_of_doors>4 doors</number_of_doors>
            <engine number_of_cylinder="8 cylinders"></engine>
        </car>
    </vehicle>
    <vehicle category="suv" item_number="14">
        <brand_name>Toyoto</brand_name>
        <description>In great condition.</description>
        <quantity>3 available</quantity>
        <car year="2016" model="Impala" carType="fuel" manufacturer="Toyota">
            <color>Brown color</color>
            <price>$12000</price>
            <number_of_doors>4 doors</number_of_doors>
            <engine number_of_cylinder="8 cylinders"></engine>
        </car>
    </vehicle>
    <vehicle category="suv" item_number="15">
        <brand_name>Toyoto</brand_name>
        <description>In great condition.</description>
        <quantity>3 available</quantity>
        <car year="2020" model="Impala" carType="fuel" manufacturer="Toyota">
            <color>Silver color</color>
            <price>$19000</price>
            <number_of_doors>4 doors</number_of_doors>
            <engine number_of_cylinder="8 cylinders"></engine>
        </car>
    </vehicle>
    <vehicle category="suv" item_number="16">
        <brand_name>Mercedes</brand_name>
        <description>Great SUV for a family.</description>
        <quantity>1 available</quantity>
        <car year="2016" model="Impala" carType="fuel" manufacturer="Toyota">
            <color>Silver color</color>
            <price>$20000</price>
            <number_of_doors>4 doors</number_of_doors>
            <engine number_of_cylinder="8 cylinders"></engine>
        </car>
    </vehicle>
</vehicle_shop>
